### ISSUE TITLE
Prebuilt raspberry pi 3 image

### ISSUE THREAD

**Issue by cookiengineer** [webosose/build-webos#1]
Hey guys,

first off: As a former webos dev during the palm pre and palm pre 2 days, I have to pay my respects. The new architecture looks amazing, and is really well thought-through. Enact, wayland, mojo, pretty much everything looks very good and is very well engineered.

Anyways, I wanted to ask whether there's a prebuilt image for Raspberries so that people can get started easier when they don't have 100GB available?

It also might make sense to have some prebuilt libraries available in different architectures, using a lazy-cache mechanism similar to ninja or others - so that e.g. chromium does not have to be built from scratch (assuming it takes a lot of space, memory and compile time; currently still digging through the tutorial).

**Comment by chbae** [comment]
@cookiengineer 
Thanks for your suggestion.

Actually yocto provides shared state change (https://www.yoctoproject.org/docs/current/ref-manual/ref-manual.html#shared-state-cache) for fast build. Unfortunately we don't provide the shared state cache yet. I will discuss your suggestion internally and reply soon.

**Comment by Vipeax** [comment]
@cookiengineer, if it helps you in any way for the time being: [webos-image-raspberrypi3.rootfs.rpi-sdimg](https://www.rvdboorn.nl/webos-image-raspberrypi3.rootfs.rpi-sdimg).

**Comment by chbae** [comment]
@Vipeax Thanks for providing built image.
@cookiengineer We don't have plan to provide prebuilt libraries and you can build webOS OSE using your desktop and share your shared state in your local. Then your second build uses the your shared state cache.

**Comment by chbae** [comment]
@pushpendrak 
Could you create new issue about Qt development guide?

**Comment by Herrie82** [comment]
@pushpendrak On LuneOS based on Open webOS (HP's open sourced version, not too different from LG's version) we developed a number of Qt Apps like:

https://github.com/webos-ports/org.webosports.app.firstuse
https://github.com/webos-ports/org.webosports.app.browser
https://github.com/webos-ports/org.webosports.app.camera
https://github.com/webos-ports/org.webosports.app.phone
https://github.com/webos-ports/org.webosports.app.settings/tree/qml-based

A project we reused from SFOS/Mer was Fingerterm:
https://github.com/webOS-ports/meta-webos-ports/blob/pyro/meta-luneos/recipes-luneos/apps/fingerterm.bb

Recipes for our QML apps can be found at: 
https://github.com/webOS-ports/meta-webos-ports/tree/pyro/meta-luneos/recipes-luneos/apps

This should in general work on webOS OSE as well, however on LuneOS we're already on Qt 5.9.4. So there might be some new features that aren't in Qt 5.6 used by webOS OSE.

Unfortunately we don't really have a guide for it, but the recipes + code should give you some ideas :)

**Comment by webOS101** [comment]
@Herrie82 Can you move this response to #2?

**Comment by CorentinDy** [comment]
Hey, thank's for the prebuilt image ! 

Did it run perfectly on your raspberry ? I've write it on my sd card and boot it up but i've only a nice wallpaper , my mouse and nothing else, any idea ?

**Comment by CorentinDy** [comment]
Thank's so much , i'll try as soon as i can. I Feel dumb now ^^ And thx for the forum, didn't knew it existed

**Comment by pushpendrak** [comment]
I tried with F1, menu popup, but clicking on items results nothing.🙄
We need better built image, which is possibly can be done by LG.

**Comment by futurejones** [comment]
I have downloaded and tested that image on my Raspberry pi, everything seems to work as expected.
All menu items work. 
Make sure you have a network connection and maybe try a different mouse.

**Comment by ranjana-panwar** [comment]
@Vipeax : I have downloaded the image, and tested it to Raspberry pi, its working but in the menubar, only webos and youtube is availble others are missing.

**Comment by CorentinDy** [comment]
As the webos is at an early stage, it might be missing some features wich need to be more stable before a public release.

**Comment by Vipeax** [comment]
@ranjana-panwar what are you missing? This is how the repo was upon release. The browser was never actually included in the release if that is what you are missing.

**Comment by ranjana-panwar** [comment]
@Vipeax : actually the settings option is not there.

**Comment by Vipeax** [comment]
I'm afraid that I'll have to throw in a 'works on my machines' here.

**Comment by ranjana-panwar** [comment]
@Vipeax 
![img20180329102240 1](https://user-images.githubusercontent.com/37827786/38070933-1d02f9e2-333c-11e8-8788-4de8e298b12d.jpg)
![img20180329102258](https://user-images.githubusercontent.com/37827786/38070934-1d31210a-333c-11e8-95cf-13b8875f95d2.jpg)

**Comment by symbios24** [comment]
Vipeax can you re upload the image link is not working

Thanks

**Comment by FabioLolix** [comment]
@symbios24 @PrateekSB 

Found this link from the forum http://build.webos-ports.org/webosose/raspberrypi3/

**Comment by mshaz** [comment]
how do u connect it to wifi? Cant find anything on screen.
