### ISSUE TITLE
Bad code (or possibly practice of it)

### ISSUE THREAD

**Issue by TomOR1** [webosose/build-webos#10]
Hi, I've recently stumbled across WebOS OS and thought that it looked awesome (which it is); this was a huge relief to me because I had one or two spare Raspberry pi 3s and could replace my TV's god-awful default Netflix experience which doesn't output to digital audio and therefore isn't compatible with my amp . There is only one huge problem: I can't find any pre-built binaries and when I try to build it myself I get a wall of errors. It is bad practice to release a project and expect every user to spend an hour or so setting up an Ubuntu VM (because barely anyone uses dual boot and fewer have a good Ubuntu setup lying around) and then waiting for it to build an image. Another reason for this being bad practice is not everyone will get the same result (and in my case, people can get errors). Here's what I've done:

1. Setup an Ubuntu VM with the recommended no. of cores (4), 9GB of RAM (1GB more than the minimum) and a 20GB disk (because this is a bare-bones install of Ubuntu which leaves 16 GB free for an 8GB OS (as per the SD card recommendations)). The cores are running at 4GHz and are not hyperthreaded.

2. Installed Ubuntu raw (meaning not Ubuntu Studio or anything) ver 18.04 in the minimum version (excluding office etc. but with the additional drivers just in case)

3. Following [this](http://webosose.org/discover/setting/building-webos-ose/) I cloned the repo into a 0777 permission folder which I owned and was in my user domain and all of the rest NOT USING `sudo su root` and as the base user for the VM and under rapi 3 settings without setting parallelism values.

4. Get an error by running either 
`$ source oe-init-build-env 
$ bitbake webos-image`

or

`make webos-image`

Which reads the following:

![image](https://user-images.githubusercontent.com/21348612/43040615-9d23be8c-8d40-11e8-9e86-13dadbe7f576.png)

and

![image](https://user-images.githubusercontent.com/21348612/43040627-bce600f4-8d40-11e8-94e3-81ea5cbc17ea.png)

I would appreciate any help that I can get. Bear in mind that I've never had to build an OS or anything on Ubuntu before (or any Linux platform) and I'm used to just hitting `Ctrl + B` or `F5` in .NET. I would also like it if you would include the binaries since additional space on GitHub doesn't cost (or at least it doesn't on GItLab) and I know that you probably have them because you'd had to have used them for QA or at least to make sure that it builds,

Thomas

**Comment by TomOR1** [comment]
I also know about [https://www.rvdboorn.nl/webos-image-raspberrypi3.rootfs.rpi-sdimg](rvdboorn.nl/webos-image-raspberrypi3.rootfs.rpi-sdimg) but I've tried multiple times over the past week to access it but it's been down all of that time.

**Comment by chbae** [comment]
That's ubuntu 18.04 problem and I request a patch to merge bitbake's 1.32 branch (https://patchwork.openembedded.org/patch/152974/). And then I'll update webOS's bitbake repo.

Please use https://patchwork.openembedded.org/patch/152974/.

**Comment by TomOR1** [comment]
Hi @chbae, I have literally never used Python in my life; could you please tell me how to apply that patch. Thanks for responding all the same!

**Comment by rip3rs** [comment]
http://webosose.org/discover/setting/building-webos-ose/

> Also, the BitBake sanity check will issue a warning if you're not running under Ubuntu 14.04 LTS 64-bit.

**Comment by chbae** [comment]
We resolved this problem. You can choose two options. Now we support ubuntu 14.04, 16.04, 18.04 64bit.
1. https://github.com/webosose/build-webos/commit/9076be398c773577a5cfda4d9e1410d6b1aaa2e6
2. https://github.com/webosose/build-webos/commit/9ff90c5390982f7b1af2fd677b41a7ccee7499c7
