### ISSUE TITLE
the system on virtualbox stops loading at the same place.

### ISSUE THREAD

**Issue by michaeltex** [webosose/build-webos#17]
![Screenshot_1](https://user-images.githubusercontent.com/10227498/70992999-acf2c100-20d3-11ea-81fd-0ae96dc0c2bc.jpg)
I did everything according to the guide: https://www.webosose.org/docs/tools/sdk/emulator/emulator-user-guide/
what could be wrong?

**Comment by heegoo-han** [comment]
Hi,
seems you are using virtualbox 5.2.
Please try latest one like 6.x.

**Comment by michaeltex** [comment]
You are absolutely right, everything worked out, thanks🙏

**Comment by heegoo-han** [comment]
Oh, Good.
