### ISSUE TITLE
SSD with exFat is not supported in LG Tv

### ISSUE THREAD

**Issue by abdulazizalmass** [webosose/build-webos#23]
Thanks for the lovely open source

After buying an SSD, San disk, I was surprised after plugged in the ssd drive that LG tv is not supporting exFat file system. And the tv response is to format my ssd to ntfs.  Would you please update this and a support to exFat? exFat is a universal file system which gives the freedom read/write any data from Mac/linux or Windows. Ntfs is limited to windows. 

Your response is appreciated

**Comment by mreith101** [comment]
NTFS drivers exist for a unix operating systems as well. Just saying.

**Comment by abdulazizalmass** [comment]
> NTFS drivers exist for a unix operating systems as well. Just saying.

I only had SSD at that time, so the only solution came to mind is using mi Xiaomi box which temporarily does the job
