### ISSUE TITLE
"404 Not Found" For Prebuild

### ISSUE THREAD

**Issue by cheznewa** [webosose/build-webos#29]
[The Prebuilds](http://build.webos-ports.org/webosose/) (qcow2 and raspberry pi) is unavaliable return a 404 error "Not Found" so i required to build self, but if i an error during build i cant no using.

**Comment by shr-project** [comment]
See https://forum.webosose.org/t/pre-built-images-available/392/70

**Comment by Heeam-Shin** [comment]
Pre-built images are re-available 🎊

https://github.com/webosose/build-webos/releases

**Comment by cheznewa** [comment]
Thank You!
