### ISSUE TITLE
bitbake build error when building mesa_native for raspberrypi3 target

### ISSUE THREAD

**Issue by therealbstern** [webosose/build-webos#3]
My build is breaking when I try to build mesa_native.

`ERROR: Task (/usr/local/src/build-webos/webosose/meta-webosose/meta-webos/recipes-graphics/mesa/mesa-native_17.1.7.bb:do_install) failed with exit code '1'`

I've attached the logfiles, instead of including them inline, because they're really long.

[log.do_install.16067 (txt)](https://github.com/webosose/build-webos/files/1840067/log.do_install.16067.txt)
[bitbake console output (txt)](https://github.com/webosose/build-webos/files/1840068/bb-console.txt)

**Comment by chbae** [comment]
You may use 32bit linux for host and I recommend that you use ubuntu 14.04 64bit. Thanks

**Comment by therealbstern** [comment]
Understood, thanks for identifying the problem.
