### ISSUE TITLE
How to download webos header and source files only?

### ISSUE THREAD

**Issue by craigcarnell** [webosose/build-webos#34]
I just want to download the web os (open source) sdk without all the tool chain etc?

I want to start looking at 
#include <wayland-webos-shell-client-protocol.h>
etc.

https://github.com/webosose/samples/blob/master/native-apps/external/com.sample.waylandegl/src/wayland_egl.c#L23

Thanks!

**Comment by shr-project** [comment]
https://github.com/webosose/webos-wayland-extensions/tree/master/protocol

**Comment by craigcarnell** [comment]
@shr-project I've seen those. But they are just xml files and not the actual headers and c source files?

**Comment by shr-project** [comment]
Just use wayland-scanner on them as described in CMake

https://github.com/webosose/webos-wayland-extensions/blob/620680a4721a7de5da8bbb87e021afd78c493898/cmake/wayland.cmake

As you were building whole webOS OSE image before, you can build just this recipe with "bitbake webos-wayland-extensions" and it will do it for you (without building any unnecessary dependencies).

**Comment by craigcarnell** [comment]
@shr-project I don't speak CMake :)

git clone https://github.com/webosose/build-webos.git
./mcf -p 2 -b 2 raspberrypi4 (tried 8, then 4, now trying 2) - I have 8 core CPU with 16 GB
(let it do it's thing)

bitbake webos-wayland-extensions
```
bitbake: command not found
```

Do I need to run make <something> first?

**Comment by shr-project** [comment]
`source oe-init-build-env`

**Comment by craigcarnell** [comment]
Also, if I want to include the headers in my project, do I just copy across

```
webos-wayland-extensions/usr/include
```

Into my project and link against existing wayland source & libs I already have?
