### ISSUE TITLE
Cant find pre-build images 

### ISSUE THREAD

**Issue by Qbers13** [webosose/build-webos#35]
Website says that they "provides pre-built images of webOS OSE platform" and they "decided to publish them using GitHub Releases" but i cant find that images anywhere.

**Comment by Heeam-Shin** [comment]
@Qbers13,

Images are available on the [Release page](https://github.com/webosose/build-webos/releases).

Pre-built images will be uploaded 2~3 days after the source codes are released. (Refer to [Blog news](http://localhost:1313/blog/2023/02/17/webos-ose-2-20-0-release/#pre-built-image-available-on-github))
