### ISSUE TITLE
RISC-V target for WebOS OSE

### ISSUE THREAD

**Issue by pdp7** [webosose/build-webos#41]
I would like to run WebOS OSE on a RISC-V RV64GC target such as the VisionFive 2 which is supported by meta-riscv (https://github.com/riscv/meta-riscv).  Has anyone tried building WebOS OSE for RISC-V yet?

**Comment by Herrie82** [comment]
@pdp7 I guess not, I have LuneOS running on a PineTab2 using Yocto. I know there are PineTab-V distro(-s) using Yocto for PineTab-V. I guess it should be fairly easy to piggyback on that for getting it LuneOS or webOS OSE running on it (we share 90% of the same DNA ;)). Happy to explore together with you :)
