### ISSUE TITLE
webos-image-qemux86-64.rootfs.wic.vmdk fails to boot in VirtualBox

### ISSUE THREAD

**Issue by pdp7** [webosose/build-webos#42]
I download webos-image-qemux86-64.rootfs.wic.vmdk from https://github.com/webosose/build-webos/releases/tag/v2.25.0 and I trying to use it in VirtualBox using these instructions:
https://www.webosose.org/docs/tools/sdk/emulator/virtualbox-emulator/emulator-user-guide/

![Screenshot from 2024-02-01 14-06-31](https://github.com/webosose/build-webos/assets/313864/90f2262b-a2a9-4e0e-9b04-31ced30effa7)

However, there is no output after "Booting kernel."
![Screenshot from 2024-02-01 14-07-30](https://github.com/webosose/build-webos/assets/313864/5d743bc4-fa37-40d2-9cf0-82c3a5a38418)

**Comment by SeongCheolHeo** [comment]
Hi
When I checked your screenshot file of virtual box settings, there is wrong settings. 
Please check it again https://www.webosose.org/docs/tools/sdk/emulator/virtualbox-emulator/emulator-user-guide/ .
For example, Select - Graphic Controller : VMSVGA and Enabled 3D Acceleration.
![image](https://github.com/webosose/build-webos/assets/3174625/7766664d-6f90-4c27-99a5-305d43f9e846)

**Comment by pdp7** [comment]
Thank you for your help. I've configured the Display correctly and it is now working.

![Screenshot from 2024-02-05 08-23-14](https://github.com/webosose/build-webos/assets/313864/7781db77-6c90-4a37-9ad0-956c2a1db1a0)

![Screenshot from 2024-02-05 08-24-11](https://github.com/webosose/build-webos/assets/313864/534eca83-426c-40bd-9f59-fd736e74c5b5)

![Screenshot from 2024-02-05 08-23-41](https://github.com/webosose/build-webos/assets/313864/3932571d-1eab-45ff-bacb-defdc8fa547e)
