### ISSUE TITLE
Devel images give black screen instead of LSM

### ISSUE THREAD

**Issue by Herrie82** [webosose/build-webos#44]
Normal image works, however dev images only show a black screen.

Using exact the same settings, so I know the settings of the VirtualBox appliance are correct.

The devel images just boot to black screen. I can get in via SSH on port 6622 to pull logs. luna-send allows me to launch com.webos.app.enactbrowser as well.

Log:
https://termbin.com/uhpt

@SeongCheolHeo

@Heeam-Shin

**Comment by Tofee** [comment]
I investigated the issue a bit, and it comes down to libpci3: when it is installed, we get a black screen.

Minimal workaround inside an ssh shell in the image is:
```
mv /usr/lib/libpci.so.3.7.0 /usr/lib/libpci.so.3.7.0.old
```

**Comment by Heeam-Shin** [comment]
@Herrie82,

This issue was already resolved in dev. internal version. It will be resolved in webOS OSE 2.26.0. Thanks 😁

**Comment by Herrie82** [comment]
Great thanks!
