### ISSUE TITLE
localization-tool-native-1.11.0-r9 do_fetch error

### ISSUE THREAD

**Issue by chisun-joung** [webosose/build-webos#48]
When I run "bitbake webos-image-devel"   There is 2 Error. because  the master branch is not existed. 
device_type : qemux86-64
git checkout 2.20

`ERROR: localization-tool-native-1.11.0-r9 do_fetch: Fetcher failure: Unable to find revision 9ac1b6554a0e4ce54da7c7ebbd581877b7330055 in branch master even from upstream
ERROR: localization-tool-native-1.11.0-r9 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/iLib-js/ilib-loctool-webos-dist.git;branch=master;protocol=https')
`

**Comment by Heeam-Shin** [comment]
Hi @chisun-joung 

This issue is caused by building from an older version.
Do not checkout to `2.20`, use `master` branch.
