### ISSUE TITLE
qtmultimedia is not compatible with the current version of Qt.

### ISSUE THREAD

**Issue by Huyle1411** [webosose/build-webos#49]
I create built-in native app and got build error related to qtmultimedia when I add this module to .bb file. Error log as below:

```
qtmultimedia was skipped: Recipe will be skipped because: fails to build: qtmultimedia/6.0.0-r1/git/src/qtmultimediaquicktools/qsgvideonode_texture.cpp:56:30: error: 'class QSGRhiSupport' has no member named 'isRhiEnabled'. http://gecko.lge.com:8000/Errors/Details/565741
qtmultimedia was skipped: Recipe will be skipped because: fails to build: qtmultimedia/6.0.0-r1/git/src/qtmultimediaquicktools/qsgvideonode_texture.cpp:56:30: error: 'class QSGRhiSupport' has no member named 'isRhiEnabled'. http://gecko.lge.com:8000/Errors/Details/565741
```

There are no build errors with other modules like qtdeclarative or qtwayland. As far as I know, this error is due to incompatibility with the current Qt version. Please patch the code to update isRhiEnabled in the QSGRhiSupport class.

Additional information: I simply run the command build: bitbake qtmultimedia, and the same error occurs. So it must be an error of Qt in this build-webos

**Comment by jaeyoonjung** [comment]
Hi,

qtmultimedia has been revamped in Qt 6 with a number of API changes and since then it hasn't been working in webOS.
So, unfortunately, it is not supported and there's no plan for that at the moment.

**Comment by Huyle1411** [comment]
> Hi,
> 
> qtmultimedia has been revamped in Qt 6 with a number of API changes and since then it hasn't been working in webOS. So, unfortunately, it is not supported and there's no plan for that at the moment.

Ok, so based on the information from https://www.webosose.org/docs/reference/ls2-api/com-webos-media/, it is highly recommended that developers avoid using _com.webos.media_ directly. Therefore, what are alternative ways for using media APIs in developing a **built-in native app** if QtMultimedia is not an option?

**Comment by Heeam-Shin** [comment]
Please use https://www.webosose.org/docs/reference/umediaclient-api/umediaclient-api-reference/ in umediaclient library, instead of https://www.webosose.org/docs/reference/ls2-api/com-webos-media/.
