### ISSUE TITLE
Video perfomance

### ISSUE THREAD

**Issue by mrsln** [webosose/build-webos#5]
Hi!
Using pre-installed test apps I was able to navigate to a page in my local network. The page only has a `<video />` tag. I found out that mp4 HD videos freeze for a second every several seconds but it plays smoothly when the video quality is 360p. However, the Youtube app is able to play crispy HD videos smoothly. How can I achieve the same quality?
Thank you!

**Comment by chbae** [comment]
@mrsln 
webOS OSE doesn't support H/W acceleration for HTML5 video tag. So the mp4 HD videos using video tag is not played well. Maintainer of webOS OSE multimedia will reply you soon.

**Comment by xxx0202xxx** [comment]
@mrsln @chbae 
The source code has limitation of using H/W acceleration about HTML5 video tag.
So you can get a performance issue in this case.

I will consider supporting H/W acceleration in the next update for the HTML5 video tag.

Thanks

**Comment by mrsln** [comment]
Thank you very much for the reply!
Do you have any idea how Youtube app is able to play crispy videos?

**Comment by chbae** [comment]
> Do you have any idea how Youtube app is able to play crispy videos?
That does not use video tag and webOS OSE supports H/W acceleration in Media Source Extensions case like youtube.

**Comment by rip3rs** [comment]
hmmm could it be because VTG is enabled even in horizontal mode?
From LG DS by using texture on the video tag it enables the rotation of the video but by doing so, CSS translateX animations tend to stutter.
by doing a css `body { transform: rotate(90deg) }` the video will rotate accordingly.
Could it be that VTG is ALWAYS on?

**Comment by SangrokKang** [comment]
@rip3rs I don't think that VTG is working on webOS OSE. VTG is only applied to the webOS Signage product. I think that webOS OSE does not have the VTG feature.

**Comment by mrsln** [comment]
thanks @chbae! It totally worked: I got smooth hd video on RPI %)

**Comment by IuriiStavnichuk** [comment]
@mrsln 
Using your approach, I see only a very slight stutter on my RP3, it's much better than before.
Thanks a lot!

**Comment by SteffenDE** [comment]
The HTML5 video tag seems to work just fine on a Raspberry Pi 4 and the latest 2.1.0 build. Great work!
