### ISSUE TITLE
API for taking screenshots

### ISSUE THREAD

**Issue by ilyai** [webosose/build-webos#8]
I'm wondering what methods are available for taking screenshots in png or jpeg format. I've searched there: http://webosose.org/develop/ls2-api/ls2-api-reference/ and couldn't find any related method.

In X11 environment our application is able to take screenshots using AWT, but on WebOS it's not working.

The error I'm getting is:

    java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.

Also tried ':0.0' value for DISPLAY variable, same error.

**Comment by ilyai** [comment]
The error I'm getting is:

    java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.

Also tried ':0.0' value for DISPLAY variable, same error.

**Comment by rabzu** [comment]
Alos XWayland does not seem to be available on the WebOS OSE build for r-pi

**Comment by chbae** [comment]
webOS doesn't work on X11 environment.
Please see http://forum.webosose.org/t/capturing-screenshots-on-webos/326/5 for capture API

**Comment by rabzu** [comment]
@chbae any update on this?

**Comment by Heeam-Shin** [comment]
Use one of the followings:

- ```luna-send -f -n 1 luna://com.webos.surfacemanager/captureCompositorOutput '{"format":"JPG","displayId":0,"output":"/tmp/screenshots/before.jpg"}'```
- `Ctrl` + `Shift` + `Alt` + `F9`
